# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - /
    exclude:
    - docs/*

# should trigger builds for PRs targeting any of the listed branches
# should _not_ trigger builds for PRs that _only_ have changes in the docs folder
# should trigger builds for PRs that have changes in both docs folder _and_ any other folder besides docs
pr:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - /
    exclude:
    - docs/*

pool:
  # todo: we dgaf what specific version of Linux is installed, is there any way to wildcard the version?
  vmImage: 'Ubuntu-16.04'

variables:
  isDev: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/dev')]

steps:
- script: |
    npm ci
  displayName: 'npm ci'
- script: |
    npm run bootstrap:ci
  displayName: 'bootstrapping packages'
- script: |
    npm run build-packages
  displayName: 'building packages'
- script: |
    npm run lint-packages
  displayName: 'linting packages'
- script: |
    npm run lint-apps
  displayName: 'linting apps'
- script: |
    npm run test-packages
  displayName: 'running tests'
  env: {
    testEnv: 'ci'
  }
- script: |
    git config user.email builds@sitecore.com
    git config user.name "Automated Build"
    git remote set-url origin https://nickwesselman:$GITHUB-PAT-ENV@github.com/Sitecore/jss.git
    $(npm bin)/lerna version prerelease --preid canary
  displayName: 'pre-release version update'
  condition: and(succeeded(), eq(variables.isDev, true))
  env:
    GITHUB-PAT-ENV: $(GITHUB-PAT)
- script: 
    echo //registry.npmjs.org/:_authToken=${NPM-TOKEN-ENV} > .npmrc
    $(npm bin)/lerna publish from-git --canary --pre-dist-tag canary --preid canary
  displayName: 'pre-release canary publish'
  condition: and(succeeded(), eq(variables.isDev, true))
  env:
    NPM-TOKEN-ENV: $(NPM-TOKEN)